### ISSUE TITLE
Install deb.torproject.org-keyring package

### ISSUE THREAD

**Issue by conorsch** [systemli/ansible-role-hidden-service#14]
The role doesn't currently install the official Tor Project keyring Debian package, which manages the apt key over time. I think it should. There are other common packages such as `torsocks` that users may wish to include in their tor configuration.

The most reasonable solutions are to add the `deb.torproject.org-keyring` package by default, and update the `apt_key` task to write to the same keyring the keyring package uses (`/etc/apt/trusted.gpg.d/deb.torproject.org-keyring.gpg` rather than `/etc/apt/trusted.gpg`).

To support extra tor-related packages, perhaps a list var is warranted, defaulting to empty, so folks can feed in vars and customize the config without affecting current default behavior of the role.

**Comment by t2d** [comment]
I think you are talking about two separate issues here.
1) deb.torproject.org-keyring
2) other tor related packages

I don't think we should include 2) into this role. Just because it is not focus of the role. Also, it's imo not the topic of this issue ;)

About 1) Since we have to manage `torproject.asc` anyway for bootstraping the repo, I see no benefit in adding the package. Can you please explain the benefit?
Apart from this, I also see no harm in it...

**Comment by conorsch** [comment]
> I don't think we should include 2) into this role. Just because it is not focus of the role. Also, it's imo not the topic of this issue ;)

Fair point! I mostly mention 2) because it would provide a solid resolution to 1), making the role more extensible, but without changing the default behavior of the role. 

> Can you please explain the benefit?

It's what the official Tor Project docs for setting up Tor on Debian recommend: https://www.torproject.org/docs/debian The tor project signing key [has expired in the past](https://trac.torproject.org/projects/tor/ticket/12994) and it surprised people; including the keyring package would make sure that doesn't happen anymore—assuming unattended-upgrades are configured.

**Comment by t2d** [comment]
Well, I'm not against it. I think, doing apt  on a list, with only `deb.torproject.org-keyring` in there by default, would by my favorite way to do it.

**Comment by conorsch** [comment]
Can do, will submit a PR.
