### ISSUE TITLE
Reasonable defaults

### ISSUE THREAD

**Issue by t2d** [systemli/ansible-role-hidden-service#7]
Thanks for #6 - great commit.
However, the multiple host config should not be in the defaults. It should be documented in the README. I think just doing a hidden service on port 22 is a reasonable default.

**Comment by xshadow** [comment]
It's already in 9797a69c1da50ded699df33e1f4c6e68b5f26149

**Comment by t2d** [comment]
great. To my knowledge, the "Role Variables" should repeat the defaults.
The example variables should be under "Example Playbook".
